package Users;

import FoodModels.Food;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;

/**
 * This class represents premium users, who have additional features and benefits compared to regular users.
 */
public class PremiumUser extends User{

    private int numberOfDietsGenerated;

    /**
     * Constructs a PremiumUser object with the specified name, password, email, and userData.
     * @param name the name of the premium user
     * @param password the password of the premium user
     * @param email the email of the premium user
     * @param userData the user data of the premium user
     */
    public PremiumUser(String name, String password, String email, UserData userData) {
        super(name, password, email, userData);
        this.numberOfDietsGenerated = 0;
    }

    /**
     * Constructs an empty PremiumUser object.
     */
    public PremiumUser() {
    }

    /**
     * Sets the number of diets generated by the premium user.
     * @param numberOfDietsGenerated the number of diets generated
     */
    public void setNumberOfDietsGenerated(int numberOfDietsGenerated) {
        this.numberOfDietsGenerated = numberOfDietsGenerated;
    }

    /**
     * Returns the number of diets generated by the premium user.
     * @return the number of diets generated
     */
    public int getNumberOfDietsGenerated() {
        return numberOfDietsGenerated;
    }

    /**
     * Increments the number of diets generated by the premium user by one.
     */
    public void addMaxDiet() {
        numberOfDietsGenerated++;
    }

    /**
     * Returns a string representation of the PremiumUser object.
     * @return a string representation of the PremiumUser object
     */
    @Override
    public String toString() {
        return super.toString() + "\n" +
                "numberOfDietsGenerated=" + numberOfDietsGenerated;
    }

    @Override
    public JSONObject toJSON() throws JSONException {
        JSONObject jsonObject = super.toJSON();
        jsonObject.put("diets_generated",numberOfDietsGenerated);
        return jsonObject;
    }

    @Override
    public void fromJSON(JSONObject jo) throws JSONException
    {
        super.fromJSON(jo);
        setNumberOfDietsGenerated(jo.getInt("diets_generated"));
    }


}
